INSERT INTO GREETING (ID,GREETING) VALUES (
1,'helllllooo... from script!');
INSERT INTO GREETING (ID,GREETING) VALUES (
2,'helllllooo... from script!');
INSERT INTO GREETING (ID,GREETING) VALUES (
3,'helllllooo... from script!');
INSERT INTO GREETING (ID,GREETING) VALUES (
4,'helllllooo... from script!');
INSERT INTO MAPPING (ID,DESCRIPTION,DISPLAY_NAME,NAME,PATH) VALUES (
1,'','','','');
INSERT INTO MAPPING (ID,DESCRIPTION,DISPLAY_NAME,NAME,PATH) VALUES (
3,'','','ww','/');
INSERT INTO MAPPING (ID,DESCRIPTION,DISPLAY_NAME,NAME,PATH) VALUES (
4,'','','wa','/main');
