CREATE SEQUENCE IF NOT EXISTS SYSTEM_SEQUENCE_80BD17A7_F666_4692_8B56_DD0A205AE374 START WITH 0;
CREATE SEQUENCE IF NOT EXISTS SYSTEM_SEQUENCE_A3FF17F7_2057_4DFF_B8B5_3B86FB179F92 START WITH 0;

CREATE TABLE IF NOT EXISTS MAPPING (
	ID BIGINT PRIMARY KEY NOT NULL,
	DESCRIPTION VARCHAR(255),
	DISPLAY_NAME VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PATH VARCHAR(255) NOT NULL
);

--ALTER TABLE MAPPING ADD CONSTRAINT CONSTRAINT_5 UNIQUE(ID);
ALTER TABLE MAPPING ADD CONSTRAINT CONSTRAINT_4 UNIQUE(NAME);

--CREATE INDEX PRIMARY_KEY_5 ON MAPPING (ID);

CREATE INDEX UK_T7YD0HK57VV8DEIGKDRGVVURE_INDEX_5 ON MAPPING (PATH);

CREATE INDEX UK_TAMQYVDFEUXAGXRQYIW9ONEPO_INDEX_5 ON MAPPING (NAME);
CREATE TABLE GREETING (
    ID BIGINT PRIMARY KEY NOT NULL,
    GREETING VARCHAR(255)
);
--ALTER TABLE GREETING ADD CONSTRAINT CONSTRAINT_3 UNIQUE(ID);
